# Generated by Django 4.2.4 on 2023-08-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='shipping_place',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
