# Generated by Django 4.2.4 on 2023-09-02 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='전화번호 형식은 {010-1234-1234, 01012341234}에 20자 이하로 이루어져야 합니다.', regex='[0-9]{2,}[-]?[0-9]{4,}[-]?[0-9]{4,}')]),
        ),
    ]
