# Generated by Django 4.2.4 on 2023-08-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_buyer_shipping_address_seller_shipping_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, max_length=13, null=True),
        ),
    ]
