# Generated by Django 4.2.4 on 2023-08-31 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='parent',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='답변'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buyer', verbose_name='문의작성자'),
        ),
    ]
