# Generated by Django 4.2.4 on 2023-08-24 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0003_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=100, verbose_name='주문명')),
                ('status', models.CharField(max_length=20, verbose_name='주문 진행 상태')),
                ('address', models.CharField(max_length=50, verbose_name='배송지')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buyer', verbose_name='구매자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='상품')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller', verbose_name='판매자')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_uid', models.CharField(max_length=320, verbose_name='결제번호')),
                ('merchant_uid', models.CharField(max_length=320, verbose_name='주문번호')),
                ('purchase_type', models.CharField(max_length=20, verbose_name='결제 수단')),
                ('status', models.CharField(max_length=20, verbose_name='결제 진행 상태')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='결제일')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.buyer', verbose_name='구매자')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.order', verbose_name='주문')),
            ],
        ),
    ]
