# Generated by Django 4.2.4 on 2023-08-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='imp_uid',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='결제번호'),
        ),
    ]
