# Generated by Django 4.2.4 on 2023-08-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
