# Generated by Django 4.2.4 on 2023-08-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='buyer',
        ),
    ]
