# Generated by Django 4.2.4 on 2023-08-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Sale', 'Sale'), ('SoldOut', 'SoldOut'), ('StopSelling', 'StopSelling')], default='Sale', max_length=30, verbose_name='상태'),
        ),
    ]
