# Generated by Django 4.2.4 on 2023-08-31 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='product_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order_status',
        ),
    ]
