# Generated by Django 4.2.4 on 2023-08-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='주문 상태'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(1, 'Sale'), (2, 'SoldOut'), (3, 'StopSelling')], default=1, max_length=30, verbose_name='상태'),
        ),
    ]
