# Generated by Django 4.2.4 on 2023-08-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_image',
            field=models.CharField(default=1, max_length=300, verbose_name='썸네일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.CharField(default=1, max_length=300, verbose_name='상품이미지'),
            preserve_default=False,
        ),
    ]
