# Generated by Django 4.2.4 on 2023-08-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_thumbnail_image_productimage_image'),
        ('products', '0004_rename_status_product_product_status_and_more'),
    ]

    operations = [
    ]
