# Generated by Django 4.2.4 on 2023-08-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_order_status_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(1, 'Sale'), (2, 'SoldOut'), (3, 'StopSelling')], default='Sale', max_length=30, verbose_name='상태'),
        ),
    ]
